[package]
name = "osapi"
version = "0.1.0"
edition = "2024"

[lib]
name = "osapi"
source = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
